// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resource_Money)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resource_Water)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resource_Oxygen)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resource_Power)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Callouts_Flag)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Callouts_Flag_Powerlines_Down)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Callouts_Flag_Chemical_Spill)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Callouts_Flag_Explosions)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Callouts_Flag_HazMat)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Realty)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Realty_Residential)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Realty_Residential_Home)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Realty_Commercial)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Realty_Commercial_Store)
